### ISSUE TITLE
~/.bashfiles/color.sh misss, Ref: Windows上的Linux工作流搭建

### ISSUE THREAD

**Issue by fimars** [thautwarm/Site-33#10]
https://thautwarm.github.io/Site-33/life/windows-workflow.html

 `~/.bashfiles/color.sh` 这个文件你是哪来的 🤔

**Comment by thautwarm** [comment]
私密马赛，偷的oh-my-zsh😘 
我更新一下

**Comment by thautwarm** [comment]
@fimars 已更新

**Comment by fimars** [comment]
阿里嘎多，辛苦了

**Comment by fimars** [comment]
去掉`@begin md` : ![image](https://user-images.githubusercontent.com/16299018/192418316-4777f4ae-4894-463d-8f26-22754d99b797.png)

现在的版本 
![image](https://user-images.githubusercontent.com/16299018/192418378-b191d57f-614e-4c6c-bbc7-10cc6e0fc898.png)


不知道你的markdown库发什么电了，好像帮你把code里的字符也处理成格式了 @thautwarm

**Comment by thautwarm** [comment]
@fimars  这些markdown库真不行🤒
