### ISSUE TITLE
UCRT64 about article 'windows-workflow'

### ISSUE THREAD

**Issue by zengjiapei3000** [thautwarm/Site-33#16]
默认环境 ucrt64 or mingw64

你好，参考了一下你的那篇文章 “Windows上的Linux工作流搭建” ，感谢你的文章指导 : ) 
我目前准备将默认环境从 mingw64 换为 ucrt64，但是 shell prompt 好像部分 emoji 显示方块。不知道是不是那一步 “但暂且先不要执行msys2命令。”，可能初始化 msys2 的时候执行了某些步骤影响了这个。我也不太懂 msys2 初始化会执行哪些工作。

---
重新安装了一遍 msys2，并且第一次启动 msys2 用的 ucrt64 subshell，还是 emoji 部分问题...看来还是老老实实用 mingw64
![0901](https://github.com/thautwarm/Site-33/assets/41148275/138df100-5798-4197-994e-39e46b52fa6b)

**Comment by thautwarm** [comment]
你好，这个和ucrt64环境无关，是字体问题。

可以从这里下载：

https://github.com/ryanoasis/nerd-fonts/tree/da88bdb61657cd3a986b7b1f72c06414a9adc715/patched-fonts/CascadiaCode/Regular/complete

**Comment by zengjiapei3000** [comment]
感谢，我按照你说的弄了一下确实好了，可能之前重装系统scoop有一点问题..
![image](https://github.com/thautwarm/Site-33/assets/41148275/2ca1e3ea-ba02-462b-839a-f00775607c65)
